### ISSUE TITLE
Generelle Anforderungen

### ISSUE THREAD

**Issue by corite** [corite/iswe#42]
Folie: Projektvorstellung Seite 10/11

**Comment by sunny1301** [comment]
**Eindeutigkeit (unambigious)**
• Jede Anforderung erlaubt nur eine Interpretation.
_-> würde ich schon sagen_
**Vollständigkeit (complete)**
• alle wesentlichen (essential) und bestimmenden Anforderungen sind niedergelegt ...
_-> haben alle wesentlichen System Features abgebildet und mindestens kurz erklärt_
• für alle möglichen (gültigen und ungültigen) Betriebszustände, Nutzereingaben … ist die Reaktion des Systems
beschrieben.
_-> ehrlicht gesagt, haben wir darüber nie wirklich gesprochen, aber in unserem Dokument sind ja Nutzereingaben in den System Featues beschrieben und wir haben Testfälle beschrieben, was passieren soll, wenn das System mal ausfällt, etc._
**Prüfbarkeit (verifiable)**
• Für jede Anforderung existiert ein realisierbarer, kosteneffektiver Prozess, anhand dessen die korrekte
Implementierung dieser Anforderung zweifelsfrei nachgewiesen werden kann.
_->Testfälle definiert und Anforderungen wurden gut beschrieben_
**Widerspruchsfreiheit (consistent)**
_-> kann ich schwer einschätzen, ich finde da steht sich nichts im Weg, höchstens die Sache mit dem Support. Wird jetzt ein Code für Benutzer und Support erstellt, wodurch beide in Kontakt treten können, oder muss der Benutzer nur ein Support-Ticket erstellen, Moritz, Bernd und Dennis meinten gestern, das steht sich nicht im Weg, und das stimmt auch, würde ich sagen, aber ich frag mich halt wie sinnvoll es ist beides drinnen zu haben, oder ob eine  Sache auch reichen würde, dann müssten wir 4.2.8, 4.2.11 und 4.3.1 nochmal bisschen umformulieren._
**Änderbarkeit (modifiable)**
• ... Minimierung von Redundanzen
_-> Admin kann Abomodelle ändern und wir haben jetzt nichts doppelt, im Gegenteil sogar, wir haben Verweise auf unterschiedliche Features, um Redundanz zu minimieren_
**Nachvollziehbarkeit (traceable)**
• Nachvollziehbarkeit (traceability)
_-> alles verständlich_
• jede Anforderung besitzt eine eindeutige Bezeichnung (Nummer)
_-> jup_
